global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'quiro_app'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'quiro_release_app'
    static_configs:
      - targets: ['release-app:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
