server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-sd
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    # transforma os metadados do docker em __path__ e labels úteis
    relabel_configs:
      # a chave que indica o caminho do arquivo de log é fornecida pelo SD
      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__

      # traz o nome do container como label
      - source_labels: [__meta_docker_container_name]
        target_label: container_name

      # label do compose (se existir)
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service

      # image do container
      - source_labels: [__meta_docker_container_image]
        target_label: image

    pipeline_stages:
      - docker: {}      # decodifica JSON do docker
      - labels:
          stream:       # keep stream label (stdout/stderr)
      - output:
          source: log   # envia o campo "log" como mensagem para o Loki
